"""
PDF/DOCX report rendering for GET /export — extends the existing CSV/JSON
export with two more downloadable formats.

Renders the exact same historical data get_historical_analytics already
returns (identical to what CSV/JSON already use — no duplicated Open-Meteo
fetch logic here, only the rendering step is new) into a readable report:
a header (zone, coordinates, date range), the derived-variable note
(reusing analytics_service.build_export_notes — the same single source of
truth CSV/JSON already call, not a second copy of that wording), a data
table (variable, date, value), and a generated-by footer.

Library choice:
- reportlab for PDF — pure-Python with no system-level dependencies (no
  Cairo/Pango, unlike weasyprint), which matters for portability across
  whatever environment this ends up deployed/demoed on.
- python-docx for DOCX — the standard, effectively only well-established
  library for this in Python.

No charts/images in this pass — a well-formatted table is enough, per the
phase brief.
"""

import io
from datetime import datetime, timezone

from docx import Document
from docx.shared import Pt
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.units import cm
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle

from backend.services.analytics_service import VARIABLE_TITLES, build_export_notes


def _generated_footer() -> str:
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    return f"Generated by ORCA · {now}"


def _build_rows(data: dict) -> list[tuple[str, str, str]]:
    """(variable label, date, formatted value) triples, grouped by
    variable (alphabetical by key, which orders sensibly since
    VARIABLE_TITLES's values are already the display names) then
    chronological within each — same tidy shape for both PDF and DOCX.

    moon_phase shows its display name (e.g. "Full Moon") instead of the
    raw 0-1 fraction — a table cell, unlike a line chart, can show either,
    and the name reads far better in a report."""
    rows: list[tuple[str, str, str]] = []
    for var in sorted(data["series"].keys()):
        series = data["series"][var]
        label = VARIABLE_TITLES.get(var, var)
        unit = series["unit"]
        names = series.get("names")
        for i, (d, v) in enumerate(zip(series["dates"], series["values"])):
            if names is not None:
                value_str = names[i] if i < len(names) else "—"
                rows.append((label, d, value_str))
                continue
            value_str = f"{v} {unit}" if v is not None else "—"
            rows.append((label, d, value_str))
    return rows


def render_pdf(zone_id: str, data: dict) -> bytes:
    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf, pagesize=A4, topMargin=2 * cm, bottomMargin=2 * cm, leftMargin=2 * cm, rightMargin=2 * cm
    )
    styles = getSampleStyleSheet()
    story = []

    story.append(Paragraph("ORCA Historical Export", styles["Title"]))
    story.append(Spacer(1, 0.3 * cm))
    story.append(Paragraph(f"<b>Zone:</b> {zone_id}", styles["Normal"]))
    story.append(Paragraph(f"<b>Location:</b> {data['lat']:.4f}, {data['lon']:.4f}", styles["Normal"]))
    story.append(Paragraph(f"<b>Date range:</b> {data['start_date']} to {data['end_date']}", styles["Normal"]))
    story.append(Spacer(1, 0.4 * cm))

    for note in build_export_notes(data["series"]):
        story.append(Paragraph(f"<i>Note: {note}</i>", styles["Normal"]))
    story.append(Spacer(1, 0.5 * cm))

    rows = _build_rows(data)
    table_data = [["Variable", "Date", "Value"]] + [list(r) for r in rows]
    table = Table(table_data, colWidths=[6 * cm, 4 * cm, 5 * cm], repeatRows=1)
    table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#0f172a")),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                ("FONTSIZE", (0, 0), (-1, -1), 9),
                ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#cbd5e1")),
                ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f8fafc")]),
                ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
                ("TOPPADDING", (0, 0), (-1, -1), 4),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
            ]
        )
    )
    story.append(table)
    story.append(Spacer(1, 0.6 * cm))
    story.append(Paragraph(_generated_footer(), styles["Normal"]))

    doc.build(story)
    return buf.getvalue()


def render_docx(zone_id: str, data: dict) -> bytes:
    doc = Document()
    doc.add_heading("ORCA Historical Export", level=1)

    meta = doc.add_paragraph()
    meta.add_run("Zone: ").bold = True
    meta.add_run(zone_id)

    loc = doc.add_paragraph()
    loc.add_run("Location: ").bold = True
    loc.add_run(f"{data['lat']:.4f}, {data['lon']:.4f}")

    rng = doc.add_paragraph()
    rng.add_run("Date range: ").bold = True
    rng.add_run(f"{data['start_date']} to {data['end_date']}")

    for note in build_export_notes(data["series"]):
        note_p = doc.add_paragraph()
        note_run = note_p.add_run(f"Note: {note}")
        note_run.italic = True

    rows = _build_rows(data)
    table = doc.add_table(rows=1, cols=3)
    table.style = "Table Grid"
    header_cells = table.rows[0].cells
    header_cells[0].text, header_cells[1].text, header_cells[2].text = "Variable", "Date", "Value"
    for run in header_cells[0].paragraphs[0].runs + header_cells[1].paragraphs[0].runs + header_cells[2].paragraphs[0].runs:
        run.bold = True
    for label, d, value_str in rows:
        cells = table.add_row().cells
        cells[0].text, cells[1].text, cells[2].text = label, d, value_str

    doc.add_paragraph()
    footer_p = doc.add_paragraph()
    footer_run = footer_p.add_run(_generated_footer())
    footer_run.italic = True
    footer_run.font.size = Pt(9)

    buf = io.BytesIO()
    doc.save(buf)
    return buf.getvalue()
